# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from MergePythonSDK.ats.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from MergePythonSDK.ats.model.access_role_enum import AccessRoleEnum
from MergePythonSDK.ats.model.account_details import AccountDetails
from MergePythonSDK.ats.model.account_details_and_actions import AccountDetailsAndActions
from MergePythonSDK.ats.model.account_details_and_actions_integration import AccountDetailsAndActionsIntegration
from MergePythonSDK.ats.model.account_details_and_actions_status_enum import AccountDetailsAndActionsStatusEnum
from MergePythonSDK.ats.model.account_integration import AccountIntegration
from MergePythonSDK.ats.model.account_token import AccountToken
from MergePythonSDK.ats.model.activity import Activity
from MergePythonSDK.ats.model.activity_type_enum import ActivityTypeEnum
from MergePythonSDK.ats.model.application import Application
from MergePythonSDK.ats.model.application_endpoint_request import ApplicationEndpointRequest
from MergePythonSDK.ats.model.application_request import ApplicationRequest
from MergePythonSDK.ats.model.application_response import ApplicationResponse
from MergePythonSDK.ats.model.attachment import Attachment
from MergePythonSDK.ats.model.attachment_endpoint_request import AttachmentEndpointRequest
from MergePythonSDK.ats.model.attachment_request import AttachmentRequest
from MergePythonSDK.ats.model.attachment_response import AttachmentResponse
from MergePythonSDK.ats.model.attachment_type_enum import AttachmentTypeEnum
from MergePythonSDK.ats.model.available_actions import AvailableActions
from MergePythonSDK.ats.model.candidate import Candidate
from MergePythonSDK.ats.model.candidate_endpoint_request import CandidateEndpointRequest
from MergePythonSDK.ats.model.candidate_request import CandidateRequest
from MergePythonSDK.ats.model.candidate_response import CandidateResponse
from MergePythonSDK.ats.model.categories_enum import CategoriesEnum
from MergePythonSDK.ats.model.category_enum import CategoryEnum
from MergePythonSDK.ats.model.data_passthrough_request import DataPassthroughRequest
from MergePythonSDK.ats.model.debug_mode_log import DebugModeLog
from MergePythonSDK.ats.model.debug_model_log_summary import DebugModelLogSummary
from MergePythonSDK.ats.model.department import Department
from MergePythonSDK.ats.model.disability_status_enum import DisabilityStatusEnum
from MergePythonSDK.ats.model.eeoc import EEOC
from MergePythonSDK.ats.model.email_address import EmailAddress
from MergePythonSDK.ats.model.email_address_request import EmailAddressRequest
from MergePythonSDK.ats.model.email_address_type_enum import EmailAddressTypeEnum
from MergePythonSDK.ats.model.encoding_enum import EncodingEnum
from MergePythonSDK.ats.model.end_user_details_request import EndUserDetailsRequest
from MergePythonSDK.ats.model.error_validation_problem import ErrorValidationProblem
from MergePythonSDK.ats.model.gender_enum import GenderEnum
from MergePythonSDK.ats.model.generate_remote_key_request import GenerateRemoteKeyRequest
from MergePythonSDK.ats.model.ignore_common_model import IgnoreCommonModel
from MergePythonSDK.ats.model.ignore_common_model_request import IgnoreCommonModelRequest
from MergePythonSDK.ats.model.issue import Issue
from MergePythonSDK.ats.model.issue_status_enum import IssueStatusEnum
from MergePythonSDK.ats.model.job import Job
from MergePythonSDK.ats.model.job_interview_stage import JobInterviewStage
from MergePythonSDK.ats.model.job_status_enum import JobStatusEnum
from MergePythonSDK.ats.model.link_token import LinkToken
from MergePythonSDK.ats.model.linked_account_status import LinkedAccountStatus
from MergePythonSDK.ats.model.meta_response import MetaResponse
from MergePythonSDK.ats.model.method_enum import MethodEnum
from MergePythonSDK.ats.model.model_operation import ModelOperation
from MergePythonSDK.ats.model.multipart_form_field_request import MultipartFormFieldRequest
from MergePythonSDK.ats.model.offer import Offer
from MergePythonSDK.ats.model.offer_status_enum import OfferStatusEnum
from MergePythonSDK.ats.model.office import Office
from MergePythonSDK.ats.model.overall_recommendation_enum import OverallRecommendationEnum
from MergePythonSDK.ats.model.paginated_account_details_and_actions_list import PaginatedAccountDetailsAndActionsList
from MergePythonSDK.ats.model.paginated_activity_list import PaginatedActivityList
from MergePythonSDK.ats.model.paginated_application_list import PaginatedApplicationList
from MergePythonSDK.ats.model.paginated_attachment_list import PaginatedAttachmentList
from MergePythonSDK.ats.model.paginated_candidate_list import PaginatedCandidateList
from MergePythonSDK.ats.model.paginated_department_list import PaginatedDepartmentList
from MergePythonSDK.ats.model.paginated_eeoc_list import PaginatedEEOCList
from MergePythonSDK.ats.model.paginated_issue_list import PaginatedIssueList
from MergePythonSDK.ats.model.paginated_job_interview_stage_list import PaginatedJobInterviewStageList
from MergePythonSDK.ats.model.paginated_job_list import PaginatedJobList
from MergePythonSDK.ats.model.paginated_offer_list import PaginatedOfferList
from MergePythonSDK.ats.model.paginated_office_list import PaginatedOfficeList
from MergePythonSDK.ats.model.paginated_reject_reason_list import PaginatedRejectReasonList
from MergePythonSDK.ats.model.paginated_remote_user_list import PaginatedRemoteUserList
from MergePythonSDK.ats.model.paginated_scheduled_interview_list import PaginatedScheduledInterviewList
from MergePythonSDK.ats.model.paginated_scorecard_list import PaginatedScorecardList
from MergePythonSDK.ats.model.paginated_sync_status_list import PaginatedSyncStatusList
from MergePythonSDK.ats.model.paginated_tag_list import PaginatedTagList
from MergePythonSDK.ats.model.phone_number import PhoneNumber
from MergePythonSDK.ats.model.phone_number_request import PhoneNumberRequest
from MergePythonSDK.ats.model.phone_number_type_enum import PhoneNumberTypeEnum
from MergePythonSDK.ats.model.race_enum import RaceEnum
from MergePythonSDK.ats.model.reason_enum import ReasonEnum
from MergePythonSDK.ats.model.reject_reason import RejectReason
from MergePythonSDK.ats.model.remote_data import RemoteData
from MergePythonSDK.ats.model.remote_key import RemoteKey
from MergePythonSDK.ats.model.remote_key_for_regeneration_request import RemoteKeyForRegenerationRequest
from MergePythonSDK.ats.model.remote_response import RemoteResponse
from MergePythonSDK.ats.model.remote_user import RemoteUser
from MergePythonSDK.ats.model.request_format_enum import RequestFormatEnum
from MergePythonSDK.ats.model.scheduled_interview import ScheduledInterview
from MergePythonSDK.ats.model.scheduled_interview_status_enum import ScheduledInterviewStatusEnum
from MergePythonSDK.ats.model.scorecard import Scorecard
from MergePythonSDK.ats.model.sync_status import SyncStatus
from MergePythonSDK.ats.model.sync_status_status_enum import SyncStatusStatusEnum
from MergePythonSDK.ats.model.tag import Tag
from MergePythonSDK.ats.model.update_application_stage_request import UpdateApplicationStageRequest
from MergePythonSDK.ats.model.url import Url
from MergePythonSDK.ats.model.url_request import UrlRequest
from MergePythonSDK.ats.model.url_type_enum import UrlTypeEnum
from MergePythonSDK.ats.model.validation_problem_source import ValidationProblemSource
from MergePythonSDK.ats.model.veteran_status_enum import VeteranStatusEnum
from MergePythonSDK.ats.model.visibility_enum import VisibilityEnum
from MergePythonSDK.ats.model.warning_validation_problem import WarningValidationProblem
from MergePythonSDK.ats.model.webhook_receiver import WebhookReceiver
from MergePythonSDK.ats.model.webhook_receiver_request import WebhookReceiverRequest
