"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.ticketing
from MergePythonSDK.ticketing.model.remote_data import RemoteData
from MergePythonSDK.ticketing.model.ticket_access_enum import TicketAccessEnum
from MergePythonSDK.ticketing.model.ticket_actions_enum import TicketActionsEnum
globals()['RemoteData'] = RemoteData
globals()['TicketAccessEnum'] = TicketAccessEnum
globals()['TicketActionsEnum'] = TicketActionsEnum
from MergePythonSDK.ticketing.model.role import Role
from MergePythonSDK.shared.api_client import ApiClient


class TestRole(unittest.TestCase):
    """Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRole(self):
        """Test Role"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Role()  # noqa: E501

        """
        No test json responses were defined for Role
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (Role,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
