"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.ticketing
from MergePythonSDK.ticketing.model.remote_field_class import RemoteFieldClass
globals()['RemoteFieldClass'] = RemoteFieldClass
from MergePythonSDK.ticketing.model.paginated_remote_field_class_list import PaginatedRemoteFieldClassList
from MergePythonSDK.shared.api_client import ApiClient


class TestPaginatedRemoteFieldClassList(unittest.TestCase):
    """PaginatedRemoteFieldClassList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedRemoteFieldClassList(self):
        """Test PaginatedRemoteFieldClassList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedRemoteFieldClassList()  # noqa: E501

        """
        No test json responses were defined for PaginatedRemoteFieldClassList
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (PaginatedRemoteFieldClassList,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
